version: "3.8"

services:
  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Restaurant/Dockerfile # Fixed path to Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test1
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile # Fixed path to Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume for data persistence

  # PostgreSQL Adminer for DB management
  adminer:
    image: adminer
    ports:
      - "8081:8080"

# Volumes to persist PostgreSQL data
volumes:
  postgres_data:
